# 网站标题
title: 正宗菌吐槽贴吧
description: 反馈校园问题平台（不知道会不会被解决）

# 使用好看的主题（just-the-docs）
remote_theme: just-the-docs/just-the-docs

# 颜色主题
color_scheme: dark

# 导航设置
aux_links:
  "GitHub仓库":
    - "https://github.com/shenjingqu/shenjingqu"

# 让首页显示内容
search_enabled: false
heading_anchors: false
